version: '3.9'

services:
  postgres:
    image: postgis/postgis:13-3.2-alpine
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - '127.0.0.1:5432:5432'
